Jet 6440
LiveViewTech/ultralytics pull request #2
Opened 2024-10-15 17:54 UTC by wjtan99

## Purpose

check in main.py that I use for training/val/test 

## Approach

How did you go about approaching the Jira acceptance criteria?
What noteworthy changes did you make that reviewers should be aware of?
Did you add new packages or change configurations?
Did you deviate from the original criteria of the Jira ticket?

## Questions

What feedback are you looking for from reviewers, general or do you have specific questions?

## TO-DOs

- A list of future items to do in order for the PR to go out.
- Links to follow-up tickets that should be done after this PR.

## Comments

Add anything else that doesn't fit into the categories above.

2024-10-15 18:53 UTC, inder123 reviewed
Let's try to do minimal changes in a third-party repository. Shall we close this PR and delete the branch? Thanks

2024-10-15 18:54 UTC, zw-lvt requested changes

2024-10-16 01:45 UTC, wjtan99 commented on main.py
> +    ap.add_argument("-p", "--pretrained", default="yolov8s.pt", help="model to use for training. default = yolov8s")
Yes we need.  We have case where the model file is available but the pretrained checkpoint is not or not fully available.  One example is the yolov8s-P2.yaml. In that case we need both.

2024-10-16 01:47 UTC, wjtan99 commented on main.py
> +        model = YOLO(args.pretrained)
There is some problem. I will fix it. 
We do need both -m and -p. See the first comment.

2024-10-17 17:28 UTC, zw-lvt approved these changes
Looks good to me.

2024-10-17 17:45 UTC, merged